import i18next from 'i18next';
import { authRoles } from '../auth';
import en from './navigation-i18n/en';
import vi from './navigation-i18n/vi';

i18next.addResourceBundle('en', 'navigation', en);
i18next.addResourceBundle('vi', 'navigation', vi);

const navigationConfig = [
  {
    id: 'dashboards',
    title: 'Dashboards',
    type: 'group',
    icon: 'heroicons-outline:home',
    translate: 'DASHBOARDS',
    children: [
      {
        id: 'dashboards.project',
        title: 'Project',
        type: 'item',
        icon: 'heroicons-outline:clipboard-check',
        url: '/dashboards/project',
      },
    ],
  },
  {
    id: 'applications',
    title: 'Applications',
    translate: 'SERVICES',
    type: 'group',
    icon: 'apps',
    children: [
      // {
      //   id: 'apps.academy',
      //   title: 'Academy',
      //   type: 'item',
      //   icon: 'heroicons-outline:academic-cap',
      //   url: '/apps/academy',
      //   translate: 'ACADEMY',
      // },
      // {
      //   id: 'apps.documentation',
      //   title: 'Documentation',
      //   type: 'item',
      //   icon: 'heroicons-outline:document-text',
      //   url: '/documentation/mock-api',
      //   translate: 'Documentation',
      // },
      {
        id: 'apps.notes',
        title: 'Notes',
        type: 'item',
        icon: 'heroicons-outline:pencil-alt',
        url: '/apps/notes',
        translate: 'NOTES',
      },
      {
        id: 'apps.tasks',
        title: 'Tasks',
        type: 'item',
        icon: 'heroicons-outline:check-circle',
        url: '/apps/tasks',
        translate: 'TASKS',
      },
      {
        id: 'apps.scrumboard',
        title: 'Scrumboard',
        type: 'item',
        icon: 'heroicons-outline:view-boards',
        url: '/apps/scrumboard',
        translate: 'SCRUMBOARD',
      },
      // {
      //   id: 'apps.indoor',
      //   title: 'Indoor',
      //   type: 'item',
      //   icon: 'heroicons-outline:office-building',
      //   url: '/apps/indoor-mapping',
      //   translate: 'INDOOR',
      // },
      {
        id: 'apps.calendar',
        title: 'Calendar',
        type: 'item',
        icon: 'heroicons-outline:calendar',
        url: '/apps/calendar',
        translate: 'CALENDAR',
      },
      {
        id: 'apps.mailbox',
        title: 'Mailbox',
        type: 'item',
        icon: 'heroicons-outline:mail',
        url: '/apps/mailbox',
        translate: 'MAIL',
        badge: {
          title: '27',
          classes: 'px-8 bg-pink-600 text-white rounded-full',
        },
      },
      {
        id: 'apps.chat',
        title: 'Chat',
        type: 'item',
        icon: 'heroicons-outline:chat-alt',
        url: '/apps/chat',
        translate: 'CHAT',
      },
      {
        id: 'apps.chatAI',
        title: 'SERVICEAI',
        type: 'item',
        icon: 'heroicons-outline:globe-alt',
        url: '/apps/service-ai',
        translate: 'SERVICEAI',
      },
      {
        id: 'apps.contacts',
        title: 'Contacts',
        type: 'item',
        icon: 'heroicons-outline:user-group',
        url: '/apps/contacts',
        translate: 'CONTACTS',
      },
    ],
  },
  // {
  //   id: 'pages',
  //   title: 'Pages',
  //   subtitle: 'Your activities',
  //   type: 'group',
  //   icon: 'heroicons-outline:document',
  //   children: [
  //     {
  //       id: 'pages.activities',
  //       title: 'Activities',
  //       type: 'item',
  //       icon: 'heroicons-outline:menu-alt-2',
  //       url: '/pages/activities',
  //     },
  //   ],
  // },
  {
    id: 'administrator',
    title: 'Administrator',
    translate: 'ADMINISTRATOR',
    type: 'group',
    icon: 'apps',
    auth: authRoles.admin,
    children: [
      {
        id: 'npssolutionsSystem',
        title: 'NPSSolutions System',
        type: 'collapse',
        icon: 'web',
        translate: 'NPSSOLUTIONS_SYSTEM',
        auth: authRoles.admin,
        children: [
          {
            id: 'usersManagement',
            title: 'Users Management',
            type: 'item',
            icon: 'material-outline:perm_identity',
            translate: 'USERS_MANAGEMENT',
            url: '/apps/users',
            auth: authRoles.admin,
          },
          {
            id: 'workspacesManagement',
            title: 'Workspaces Management',
            type: 'item',
            icon: 'business',
            translate: 'WORKSPACES_MANAGEMENT',
            url: '/apps/workspaces',
            auth: authRoles.admin,
          },
          {
            id: 'teamsManagement',
            title: 'Teams Management',
            type: 'item',
            icon: 'material-outline:people_alt',
            translate: 'TEAMS_MANAGEMENT',
            url: '/apps/teams',
            auth: authRoles.admin,
          },
          {
            id: 'systemSetting',
            title: 'System Setting',
            type: 'item',
            icon: 'settings',
            translate: 'SYSTEM_SETTINGS',
            url: '/admin/system-settings',
            auth: authRoles.admin,
          },
        ],
      },
      {
        id: 'npssolutionsRoles',
        title: 'NPSSolutions Roles',
        type: 'collapse',
        icon: 'material-outline:accessibility_new',
        translate: 'NPSSOLUTIONS_ACCESSIBILITY',
        auth: authRoles.admin,
        children: [
          {
            id: 'manageItemsApp',
            title: 'Manage Items App',
            type: 'item',
            icon: 'apps',
            translate: 'MANAGE_ITEMS_APP',
            url: '/apps/manage-items-app',
            auth: authRoles.admin,
          },
          {
            id: 'manageRolesApp',
            title: 'Manage Roles App',
            type: 'item',
            icon: 'heroicons-outline:user-group',
            translate: 'MANAGE_ROLES_APP',
            url: '/apps/manage-roles-app',
            auth: authRoles.admin,
          },
          {
            id: 'manageRoleForItem',
            title: 'Manage Role For Item',
            type: 'item',
            icon: 'material-outline:engineering',
            translate: 'MANAGE_ROLE_FOR_ITEM',
            url: '/apps/manage-role-for-item',
            auth: authRoles.admin,
          },
          {
            id: 'manageTeamForRole',
            title: 'Manage Team For Role',
            type: 'item',
            icon: 'material-outline:group_work',
            translate: 'MANAGE_TEAM_FOR_ROLE',
            url: '/apps/manage-team-for-role',
            auth: authRoles.admin,
          },
          {
            id: 'manageWorkspaceForRole',
            title: 'Manage Workspace For Role',
            type: 'item',
            icon: 'material-outline:brightness_high',
            translate: 'MANAGE_WORKSPACE_FOR_ROLE',
            url: '/apps/manage-workspace-for-role',
            auth: authRoles.admin,
          },
        ],
      },
    ],
  },
];

export default navigationConfig;
